Config = {}

Config.SilentWeapons = {
	["WEAPON_PISTOL"] = "COMPONENT_AT_PI_SUPP_02",
	["WEAPON_PISTOL50"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_COMBATPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_APPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_HEAVYPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_VINTAGEPISTOL"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_SMG"] = "COMPONENT_AT_PI_SUPP",
	["WEAPON_MICROSMG"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_ASSAULTSHOTGUN"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_BULLPUPSHOTGUN"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_PUMPSHOTGUN"] = "COMPONENT_AT_SR_SUPP",
	["WEAPON_MARKSMANRIFLE"] = "COMPONENT_AT_AR_SUPP",
	["WEAPON_SNIPERRIFLE"] = "COMPONENT_AT_AR_SUPP_02",
	["WEAPON_MACHINEPISTOL"] = "COMPONENT_AT_PI_SUPP",
}

Config.FlashLightWeapons = {
	["WEAPON_PISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_PISTOL50"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_COMBATPISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_APPISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_HEAVYPISTOL"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_SMG"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_MICROSMG"] = "COMPONENT_AT_PI_FLSH",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_COMBATPDW"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_ASSAULTSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_BULLPUPSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_PUMPSHOTGUN"] = "COMPONENT_AT_AR_FLSH",
	["WEAPON_MARKSMANRIFLE"] = "COMPONENT_AT_AR_FLSH",
}

Config.GripWeapons = {
	["WEAPON_COMBATPDW"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_ASSAULTSHOTGUN"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_BULLPUPSHOTGUN"] = "COMPONENT_AT_AR_AFGRIP",
	["WEAPON_MARKSMANRIFLE"] = "COMPONENT_AT_AR_AFGRIP",
}

Config.ExtendedMagazineWeapons = {
	["WEAPON_PISTOL"] = "COMPONENT_PISTOL_CLIP_02",
	["WEAPON_PISTOL50"] = "COMPONENT_PISTOL50_CLIP_02",
	["WEAPON_COMBATPISTOL"] = "COMPONENT_COMBATPISTOL_CLIP_02",
	["WEAPON_APPISTOL"] = "COMPONENT_APPISTOL_CLIP_02",
	["WEAPON_SNSPISTOL"] = "COMPONENT_SNSPISTOL_CLIP_02",
	["WEAPON_HEAVYPISTOL"] = "COMPONENT_HEAVYPISTOL_CLIP_02",
	["WEAPON_VINTAGEPISTOL"] = "COMPONENT_VINTAGEPISTOL_CLIP_02",
	["WEAPON_SMG"] = "COMPONENT_SMG_CLIP_02",
	["WEAPON_MICROSMG"] = "COMPONENT_MICROSMG_CLIP_02",
	["WEAPON_ASSAULTSMG"] = "COMPONENT_ASSAULTSMG_CLIP_02",
	["WEAPON_COMBATPDW"] = "COMPONENT_COMBATPDW_CLIP_02",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_ASSAULTRIFLE_CLIP_02",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_CARBINERIFLE_CLIP_02",
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_ADVANCEDRIFLE_CLIP_02",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_SPECIALCARBINE_CLIP_02",
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_BULLPUPRIFLE_CLIP_02",
	["WEAPON_COMPACTRIFLE"] = "COMPONENT_COMPACTRIFLE_CLIP_02",
	["WEAPON_MACHINEPISTOL"] = "COMPONENT_MACHINEPISTOL_CLIP_02",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_HEAVYSHOTGUN_CLIP_02",
	["WEAPON_GUSENBERG"] = "COMPONENT_GUSENBERG_CLIP_02",
}
-- rulla klipit?
--[[
Config.VeryExtendedMagazineWeapons = {
	["WEAPON_SMG"] = "COMPONENT_SMG_CLIP_03",
	["WEAPON_COMBATPDW"] = "COMPONENT_COMBATPDW_CLIP_03",
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_ASSAULTRIFLE_CLIP_03",
	["WEAPON_CARBINERIFLE"] = "COMPONENT_CARBINERIFLE_CLIP_03",
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_SPECIALCARBINE_CLIP_03",
	["WEAPON_COMPACTRIFLE"] = "COMPONENT_COMPACTRIFLE_CLIP_03",
	["WEAPON_MACHINEPISTOL"] = "COMPONENT_MACHINEPISTOL_CLIP_03",
	["WEAPON_HEAVYSHOTGUN"] = "COMPONENT_HEAVYSHOTGUN_CLIP_03",
}]]

Config.ScopeWeapons = {
	["WEAPON_SMG"] = "COMPONENT_AT_SCOPE_MACRO_02",  -- Punapiste
	["WEAPON_MICROSMG"]	= "COMPONENT_AT_SCOPE_MACRO", -- Punapiste
	["WEAPON_ASSAULTSMG"] = "COMPONENT_AT_SCOPE_MACRO", -- Punapiste
	["WEAPON_COMBATPDW"] = "COMPONENT_AT_SCOPE_SMALL", -- Tähtäin
	["WEAPON_ASSAULTRIFLE"] = "COMPONENT_AT_SCOPE_MACRO", -- Punapiste
	["WEAPON_CARBINERIFLE"] = "COMPONENT_AT_SCOPE_MEDIUM", -- Punapiste
	["WEAPON_ADVANCEDRIFLE"] = "COMPONENT_AT_SCOPE_SMALL", -- Tähtäin
	["WEAPON_SPECIALCARBINE"] = "COMPONENT_AT_SCOPE_MEDIUM", -- Punapiste
	["WEAPON_BULLPUPRIFLE"] = "COMPONENT_AT_SCOPE_SMALL", -- Tähtäin
	["WEAPON_SNIPERRIFLE"] = "COMPONENT_AT_SCOPE_MAX", -- Kehittynyt tähtäin
	["WEAPON_HEAVYSNIPER"] = "COMPONENT_AT_SCOPE_MAX", -- Kehittynyt tähtäin

}

--[[Config.AdvancedScopeWeapons = {
	["WEAPON_SNIPERRIFLE"] = "COMPONENT_AT_SCOPE_LARGE",
	["WEAPON_HEAVYSNIPER"] = "COMPONENT_AT_SCOPE_LARGE",
}]]

Config.Aseet = {
	["WEAPON_PISTOL"] = "12",
	["WEAPON_COMBATPISTOL"] = "12",
	["WEAPON_APPISTOL"] = "18",
	["WEAPON_PISTOL50"] = "9",
	["WEAPON_SNSPISTOL"] = "6",
	["WEAPON_HEAVYPISTOL"] = "18",
	["WEAPON_VINTAGEPISTOL"] = "7",
	["WEAPON_MARKSMANPISTOL"] = "1",
	["WEAPON_REVOLVER"] = "6",
	["WEAPON_MICROSMG"] = "16",
	["WEAPON_SMG"] = "30",
	["WEAPON_ASSAULTSMG"] = "30",
	["WEAPON_COMBATPDW"] = "30",
	["WEAPON_MACHINEPISTOL"] = "12",
	["WEAPON_MINISMG"] = "12",
	["WEAPON_PUMPSHOTGUN"] = "8",
	["WEAPON_SAWNOFFSHOTGUN"] = "8",
	["WEAPON_ASSAULTSHOTGUN"] = "8",
	["WEAPON_BULLPUPSHOTGUN"] = "14",
	["WEAPON_MUSKET"] = "1",
	["WEAPON_HEAVYSHOTGUN"] = "6",
	["WEAPON_DBSHOTGUN"] = "2",
	["WEAPON_ASSAULTRIFLE"] = "30",
	["WEAPON_CARBINERIFLE"] = "30",
	["WEAPON_ADVANCEDRIFLE"] = "30",
	["WEAPON_SPECIALCARBINE"] = "30",
	["WEAPON_BULLPUPRIFLE"] = "30",
	["WEAPON_COMPACTRIFLE"] = "30",
	["WEAPON_SNIPERRIFLE"] = "10",
	["WEAPON_HEAVYSNIPER"] = "6",
	["WEAPON_MARKSMANRIFLE"] = "8",
	["WEAPON_MG"] = "54",
	["WEAPON_COMBATMG"] = "100",
	["WEAPON_GUSENBERG"] = "30",
}